    - name: "Download do Wordpress"
      get_url: url=http://wordpress.org/latest.tar.gz dest=/tmp/latest.tar.gz timeout=100

    - name: "Abre wordpress em /opt/wordpress"
      unarchive: src=/tmp/latest.tar.gz dest=/opt copy=no

    - name: "Corrige permissoes"
      file: path=/opt/wordpress recurse=yes owner=www-data group=www-data
